name: bapbi_app
description: "A useful application for office workers"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flex_color_scheme: ^7.3.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  bitsdojo_window: ^0.1.6
  auto_route: ^8.0.3
  lucide_icons: ^0.257.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  url_launcher: ^6.2.5
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
